name: 'dbt_ads_channels'
version: '1.0.0'

profile: 'dbt_ads_channels'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  database: "bigquery project-id"  # Replace with your actual bigquery project ID

clean-targets:
  - "target"
  - "dbt_packages"